version: "3.9"

services:
  asset-api:
    build: .
    container_name: asset_detection_api
    ports:
      - "8000:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G